### ISSUE TITLE
JavacordCommander hasRole(...) Bug

### ISSUE THREAD

**Issue by Bourne-ID** [RealGatt/JavacordCommander#2]
Method hasRole, class JavaCommander, variable caseSensitive - if true the comparison uses equalsIgnoreCase, rather than .equals. Likewise the case insensitive search uses .equals.

**Comment by RealGatt** [comment]
Oops! I was meant to type caseInsensitive! Will be resolved.

**Comment by RealGatt** [comment]
Fixed! Will release new build within the next few days.
